apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: lucas
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: lucas
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: anna
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: anna
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: alex
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: alex
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: henry
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: henry
