name: PVPN - Terraform Management

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "terraform destroy"
        type: boolean
        required: true
        default: false

permissions:
  id-token: write
  contents: read
  issues: write

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  terraform:
    name: Terraform Management
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./personal-vpn/infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: inputs.destroy == false
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Plan Destroy
        if: inputs.destroy == true
        id: plan-destroy
        run: terraform plan -destroy -out=tfplan

      - name: Review
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: thai-nm
          minimum-approvals: 1
          issue-title: "${{ inputs.destroy && 'Destroying' || 'Provisioning' }} infrastructure"
          issue-body: "Please review Terraform ${{ inputs.destroy && 'destroy' || '' }} plan."
          exclude-workflow-initiator-as-approver: false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && inputs.destroy == false
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main' && inputs.destroy == true
        run: terraform apply -auto-approve tfplan
